### ISSUE TITLE
Warning: Undefined array key

### ISSUE THREAD

**Issue by bonomani** [splitbrain/dokuwiki-plugin-data#238]
With Php8.0, I have those warnings???
Warning: Undefined array key "optional" in /home/clients/f4b425039858465a8aa8010a2810d282/sites/wiki.ubiquitous-network.ch/lib/plugins/data/helper/aliastextbox.php on line 65

Warning: Undefined array key "value" in /home/clients/f4b425039858465a8aa8010a2810d282/sites/wiki.ubiquitous-network.ch/lib/plugins/data/helper/aliastextbox.php on line 106

**Comment by asheenlevrai** [comment]
Same here on "Kaos" (running Php8.2):

2024-04-11 10:40:26
E_WARNING: Undefined array key "dataofs"
/var/www/html/test-dokuwiki-upgrade/lib/plugins/data/syntax/table.php(528)
#0 /var/www/html/test-dokuwiki-upgrade/lib/plugins/data/syntax/table.php(528): dokuwiki\ErrorHandler::errorHandler()
#1 /var/www/html/test-dokuwiki-upgrade/lib/plugins/data/syntax/table.php(337): syntax_plugin_data_table->postList()
#2 /var/www/html/test-dokuwiki-upgrade/inc/parser/renderer.php(126): syntax_plugin_data_table->render()
#3 /var/www/html/test-dokuwiki-upgrade/inc/parserutils.php(691): Doku_Renderer->plugin()
#4 /var/www/html/test-dokuwiki-upgrade/inc/parserutils.php(158): p_render()
#5 /var/www/html/test-dokuwiki-upgrade/inc/parserutils.php(97): p_cached_output()
#6 /var/www/html/test-dokuwiki-upgrade/inc/Ui/PageView.php(67): p_wiki_xhtml()
#7 /var/www/html/test-dokuwiki-upgrade/inc/Action/Show.php(40): dokuwiki\Ui\PageView->show()
#8 /var/www/html/test-dokuwiki-upgrade/inc/template.php(120): dokuwiki\Action\Show->tplContent()
#9 [internal function]: tpl_content_core()
#10 /var/www/html/test-dokuwiki-upgrade/inc/Extension/Event.php(134): call_user_func_array()
#11 /var/www/html/test-dokuwiki-upgrade/inc/Extension/Event.php(200): dokuwiki\Extension\Event->trigger()
#12 /var/www/html/test-dokuwiki-upgrade/inc/template.php(102): dokuwiki\Extension\Event::createAndTrigger()
#13 /var/www/html/test-dokuwiki-upgrade/lib/tpl/dokuwiki/main.php(60): tpl_content()
#14 /var/www/html/test-dokuwiki-upgrade/inc/actions.php(30): include('...')
#15 /var/www/html/test-dokuwiki-upgrade/doku.php(131): act_dispatch()
#16 {main}
2024-04-11 10:40:26
E_WARNING: Undefined array key "dataflt"
/var/www/html/test-dokuwiki-upgrade/lib/plugins/data/syntax/table.php(553)
#0 /var/www/html/test-dokuwiki-upgrade/lib/plugins/data/syntax/table.php(553): dokuwiki\ErrorHandler::errorHandler()
#1 /var/www/html/test-dokuwiki-upgrade/lib/plugins/data/syntax/table.php(337): syntax_plugin_data_table->postList()
#2 /var/www/html/test-dokuwiki-upgrade/inc/parser/renderer.php(126): syntax_plugin_data_table->render()
#3 /var/www/html/test-dokuwiki-upgrade/inc/parserutils.php(691): Doku_Renderer->plugin()
#4 /var/www/html/test-dokuwiki-upgrade/inc/parserutils.php(158): p_render()
#5 /var/www/html/test-dokuwiki-upgrade/inc/parserutils.php(97): p_cached_output()
#6 /var/www/html/test-dokuwiki-upgrade/inc/Ui/PageView.php(67): p_wiki_xhtml()
#7 /var/www/html/test-dokuwiki-upgrade/inc/Action/Show.php(40): dokuwiki\Ui\PageView->show()
#8 /var/www/html/test-dokuwiki-upgrade/inc/template.php(120): dokuwiki\Action\Show->tplContent()
#9 [internal function]: tpl_content_core()
#10 /var/www/html/test-dokuwiki-upgrade/inc/Extension/Event.php(134): call_user_func_array()
#11 /var/www/html/test-dokuwiki-upgrade/inc/Extension/Event.php(200): dokuwiki\Extension\Event->trigger()
#12 /var/www/html/test-dokuwiki-upgrade/inc/template.php(102): dokuwiki\Extension\Event::createAndTrigger()
#13 /var/www/html/test-dokuwiki-upgrade/lib/tpl/dokuwiki/main.php(60): tpl_content()
#14 /var/www/html/test-dokuwiki-upgrade/inc/actions.php(30): include('...')
#15 /var/www/html/test-dokuwiki-upgrade/doku.php(131): act_dispatch()
#16 {main}


I use the "Data" plugin to aggregate "Data entries" onto "Data tables" and this still works despite the errors in the logs.

Best,
-a-
